server:
  port: ${server_port:9100}
spring:
  profiles:
    active: dev
  application:
    name: auth-service
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

# JTW Config
jwt:
  secret: ${jwt_secret:thisisathirtycharacterlongstring}
  expiration: 3600000

google:
  CLIENT_ID: 120787335948-g4r6bof29ub3vaaaiu7pc01jd5dalooq.apps.googleusercontent.com

facebook:
  TOKEN_VALIDATION_URL: https://graph.facebook.com/me?access_token=
