server:
  port: ${server_port:9500}
spring:
  application:
    name: database-server
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
