# Used for running application in isolation
spring:
  aop:
    auto: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    # Info level for all java logs
    ROOT: info
    # Switch to debug level to view custom logs
    com.cg: info
# Disables discovery CLient eatures - Use this or Confi file
eureka:
  client:
    enabled: false
