### Fetch cart by user ID method - Invalid
GET http://localhost:9300/cart/user/100000

### Fetch cart by user ID method 
GET http://localhost:9300/cart/user/100001

### Fetch cart by user ID method 
GET http://localhost:9300/cart/100001

### Checkout by user Id
POST http://localhost:9300/cart/checkout/100001

### Add item to cart - Invalid data
PUT http://localhost:9300/cart/100012
Content-Type: application/json

{
  "productId": "100003",
  "quantity": 9
}


### Add item to cart - Valid data
PUT http://localhost:9300/cart/100001
Content-Type: application/json

{
  "productId": "100001",
  "quantity": 9
}


### Delete from cart
DELETE http://localhost:9300/cart/delete/100001/100001

### Merge - Invalid data
POST http://localhost:9300/cart/merge/100001
Content-Type: application/json

{
  "itemDtoList": [
    {
      "productId": "100009",
      "quantity": 9
    }
  ]
}


### Merge 
POST http://localhost:9300/cart/merge/100001
Content-Type: application/json

{
  "itemDtoList": [
    {
      "productId": "100002",
      "quantity": 9
    },
    {
      "productId": "100001",
      "quantity": 9
    }
  ]
}

### Manual checkout
POST http://localhost:9300/cart/manualcheckout/100001
Content-Type: application/json

{
  "city": "Mumbai",
  "area": "Powai",
  "pincode": "400001",
  "state": "Maharashtra",
  "paymentId": "100002",
  "deliveryCharge": "120"
}
