### Fetch cart by user ID method - Invalid
GET http://localhost:9300/cart/user/100000

### Fetch cart by user ID method 
GET http://localhost:9300/cart/user/100001

### Fetch cart by user ID method 
GET http://localhost:9300/cart/100001

### Checkout by cart Id
POST http://localhost:9300/cart/checkout/100001

### Add item to cart - Invalid data
PUT http://localhost:9300/cart/100001
Content-Type: application/json

{
  "productId": "100001",
  "quantity": 9
}
