server:
  port: ${server_port:9600}
spring:
  profiles:
    active: dev
  application:
    name: payment-service
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

# JTW Config
jwt:
  secret: ${jwt_secret:thisisathirtycharacterlongstring}
  expiration: 3600000

stripe: 
  key: ${stripe_key:sk_test_51I3zWOI8py6Rj5ufAOC0uwcqJy64pIGVg5OK9O80NqICeXosLJYYlDKESNeD0NRTudoL6MtF6u7n6e9tjseDGnZW00JkeuTLoT}

razor:
  publicKey: rzp_test_QHK5P7ne66SdWo
  privateKey: XeaLw0YDUXDck0tfb4WzqEaX
