server:
  port: ${server_port:9300}
spring:
  profiles:
    active: dev
  application:
    name: cart-service
  mail:
    host: smtp.sendgrid.net
    port: 25
    ssl: no
    tls: yes
    username: apikey
    password: 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
    protocol: smtp
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
