
################## Hello World ##################
GET http://localhost:9000/auth-service
Authorization: Bearer [Fetch Token from login]

#############################################
### AUTH
#############################################

### Login Valid
POST http://localhost:9000/auth-service/auth/login
Content-Type: application/json

{
  "username": "gagan",
  "password": "123456"
}

### Login Invalid Field
POST http://localhost:9000/auth-service/auth/login
Content-Type: application/json

{
  "username": "gagan"
}

### Login InValid Cfredential
POST http://localhost:9000/auth-service/auth/login
Content-Type: application/json

{
  "username": "gagan",
  "password": "1234567777"
}

################## Change Password Endpoint Endpoint Tests ##################

### Fetch Question Valid Username
GET http://localhost:9000/auth-service/auth/forgotpassword/gagan

### Fetch Question Invalid Username
GET http://localhost:9000/auth-service/auth/forgotpassword/gagandeeeee


### Chage Password Request - Invalid Username
PUT http://localhost:9000/auth-service/auth/forgotpassword
Content-Type: application/json

{
  "username": "gaganzz",
  "securityAnswer": "default",
  "newPassword": "123456"
}

### Chage Password Request - Invalid Answer
PUT http://localhost:9000/auth-service/auth/forgotpassword
Content-Type: application/json

{
  "username": "gagan",
  "securityAnswer": "weeeeeeeeeee",
  "newPassword": "123456"
}

### Chage Password Request - Success
PUT http://localhost:9000/auth-service/auth/forgotpassword
Content-Type: application/json

{
  "username": "gagan",
  "securityAnswer": "answer",
  "newPassword": "123456"
}

################## Register Endpoint Tests ##################

### Register Invalid Fields

POST http://localhost:9100/register 
Content-Type: application/json

{
  "username": "gaganddd",
  "address": {
  "state": "Maharashta",
  "city": "Mumbai",
  "area": "Chandivali"
  },
  "firstName": "Gagandeep",
  "lastName": "Singh",
  "designation": "Developer",
  "gender": "Male",
  "dob": "1999-05-14",
  "emailId": "test@mail.com"
}

### Register Invalid Data
POST http://localhost:9100/register 
Content-Type: application/json

{
  "username": "gagandddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
  "address": {
  "state": "Maharashta",
  "city": "Mumbai",
  "area": "Chandivali"
  },
  "firstName": "Gagandeep",
  "lastName": "Singh",
  "designation": "Developer",
  "dob": "1999-05-14",
  "emailId": "test@mail.com"
}

### Register Valid Data
POST http://localhost:9100/register 
Content-Type: application/json

{
  "username": "gagaa",
  "address": {
  "state": "Maharashta",
  "city": "Mumbai",
  "area": "Chandivali",
  "pincode": "400072"
  },
  "firstName": "Gagandeep",
  "lastName": "Singh",
  "emailId": "test@mail.com",
  "phoneNo": "8419969059",
  "password": "12345678"
}

### Register Valid Data
PUT http://localhost:9100/register 
Content-Type: application/json

{
  "userId": "100001",
  "username": "gagana",
  "address": {
  "state": "Maharashta",
  "city": "Mumbai",
  "area": "Chandivali",
  "pincode": "400072"
  },
  "firstName": "Gagandeep",
  "lastName": "Singh",
  "emailId": "test@mail.com",
  "phoneNo": "8419969059",
  "password": "12345678",
  "securityQuestion": "What is your name",
  "securityAnswer": "123456"
}





#############################################
### Products
#############################################

### Fetch all products
GET http://localhost:9000/product-service/products

### Fetch Products by Category 
GET http://localhost:9000/product-service/products/category/Toys

### Fetch Products by Category - Invalid
GET http://localhost:9000/product-service/products/category/test

### Fetch Product by ID
GET http://localhost:9000/product-service/products/100001

### Fetch Product by ID - Invalid
GET http://localhost:9000/product-service/products/999

### Update Stocks - Invalid
PUT http://localhost:9000/product-service/products/stock
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnYWdhbiIsInVzZXJJZCI6MTAwMDAxLCJpYXQiOjE2MTEyMTk3NDAsImV4cCI6MTYxMTIyMzM0MH0.diwTe6f5ihWtdcn-4YocsrmMhn_2iyj4WZJiwd93DHk
Content-Type: application/json

{
  "productId": "100001",
  "quantity": 999
}

### Create Product - Invalid
POST http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}

### Create Product - Invalid
POST http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100999,
  "productStatus": "ENABLED"
}

### Create Product - Valid
POST http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Update Product - Null id
PUT http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Update Product - InValid id
PUT http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productId": 100099,
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Update Product - InValid id
PUT http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productId": 100001,
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 88,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Increment Stock - Invalid
PUT http://localhost:9000/product-service/products/increment
Content-Type: application/json

{
  "productId": 100099,
  "quantity": 122
}

### Increment Stock - InValid
PUT http://localhost:9000/product-service/products/increment
Content-Type: application/json

{
  "productId": 100001,
  "quantity": -3
}


### Increment Stock - Valid
PUT http://localhost:9000/product-service/products/increment
Content-Type: application/json

{
  "productId": 100001,
  "quantity": 12
}

### Decrement stock - Very high value
PUT http://localhost:9000/product-service/products/decrement
Content-Type: application/json

{
  "productId": 100001,
  "quantity": 2000
}

### Decrement stock
PUT http://localhost:9000/product-service/products/decrement
Content-Type: application/json

{
  "productId": 100001,
  "quantity": 12
}


### Fetch All categories

GET http://localhost:9000/product-service/categories

### Create Category - Invalid data
POST http://localhost:9000/product-service/categories
Content-Type: application/json

{
  "categoryDescription": "This is a dummy category description",
  "categoryImageUrl": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}

### Create category - Valid Data
POST http://localhost:9000/product-service/categories
Content-Type: application/json

{
  "categoryName": "",
  "categoryDescription": "This is a dummy category description",
  "categoryImageUrl": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}


### Create category - Valid Data
POST http://localhost:9000/product-service/categories
Content-Type: application/json

{
  "categoryName": "Dummy Category",
  "categoryDescription": "This is a dummy category description",
  "categoryImageUrl": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}

#############################################
### Cart
#############################################

### Fetch cart by user ID method - Invalid
GET http://localhost:9000/cart-service/cart/user/100000

### Fetch cart by user ID method 
GET http://localhost:9000/cart-service/cart/user/100001

### Fetch cart by user ID method 
GET http://localhost:9000/cart-service/cart/100001

### Checkout by cart Id
POST http://localhost:9000/cart-service/cart/checkout/100001

### Add item to cart - Invalid data
PUT http://localhost:9000/cart-service/cart/100012
Content-Type: application/json

{
  "productId": "100003",
  "quantity": 9
}


### Add item to cart - Valid data
PUT http://localhost:9000/cart-service/cart/100001
Content-Type: application/json

{
  "productId": "100002",
  "quantity": 9
}


### Delete from cart
DELETE http://localhost:9000/cart-service/cart/delete/100001/100001

### Merge - Invalid data
POST http://localhost:9000/cart-service/cart/merge/100001
Content-Type: application/json

{
  "itemDtoList": [
    {
      "productId": "100009",
      "quantity": 9
    }
  ]
}


### Merge 
POST http://localhost:9000/cart-service/cart/merge/100001
Content-Type: application/json

{
  "itemDtoList": [
    {
      "productId": "100002",
      "quantity": 9
    },
    {
      "productId": "100001",
      "quantity": 9
    }
  ]
}
