
################## Hello World ##################
GET http://localhost:9000/auth-service
Authorization: Bearer [Fetch Token from login]

#############################################
### AUTH
#############################################

### Login Valid
POST http://localhost:9000/auth-service/auth/login
Content-Type: application/json

{
  "username": "gagan",
  "password": "123456"
}

### Login Invalid Field
POST http://localhost:9000/auth-service/auth/login
Content-Type: application/json

{
  "username": "gagan"
}

### Login InValid Cfredential
POST http://localhost:9000/auth-service/auth/login
Content-Type: application/json

{
  "username": "gagan",
  "password": "1234567777"
}

################## Change Password Endpoint Endpoint Tests ##################

### Fetch Question Valid Username
GET http://localhost:9000/auth-service/auth/forgotpassword/gagan

### Fetch Question Invalid Username
GET http://localhost:9000/auth-service/auth/forgotpassword/gagandeeeee


### Chage Password Request - Invalid Username
PUT http://localhost:9000/auth-service/auth/forgotpassword
Content-Type: application/json

{
  "username": "gaganzz",
  "securityAnswer": "default",
  "newPassword": "123456"
}

### Chage Password Request - Invalid Answer
PUT http://localhost:9000/auth-service/auth/forgotpassword
Content-Type: application/json

{
  "username": "gagan",
  "securityAnswer": "weeeeeeeeeee",
  "newPassword": "123456"
}

### Chage Password Request - Success
PUT http://localhost:9000/auth-service/auth/forgotpassword
Content-Type: application/json

{
  "username": "gagan",
  "securityAnswer": "answer",
  "newPassword": "123456"
}


#############################################
### Products
#############################################

### Fetch all products
GET http://localhost:9000/product-service/products

### Fetch Products by Category 
GET http://localhost:9000/product-service/products/category/Toys

### Fetch Products by Category - Invalid
GET http://localhost:9000/product-service/products/category/test

### Fetch Product by ID
GET http://localhost:9000/product-service/products/100001

### Fetch Product by ID - Invalid
GET http://localhost:9000/product-service/products/999

### Update Stocks - Invalid
PUT http://localhost:9000/product-service/products/stock
Content-Type: application/json

{
  "productId": "100001",
  "quantity": 999
}

### Create Product - Invalid
POST http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}

### Create Product - Invalid
POST http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100999,
  "productStatus": "ENABLED"
}

### Create Product - Valid
POST http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Update Product - Null id
PUT http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Update Product - InValid id
PUT http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productId": 100099,
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 888,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Update Product - InValid id
PUT http://localhost:9000/product-service/products
Content-Type: application/json

{
  "productId": 100001,
  "productName": "Dummy Product",
  "productDescription": "This is a product description",
  "productPrice": 1999,
  "productStock": 88,
  "productIcon": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg",
  "categoryId": 100001,
  "productStatus": "ENABLED"
}

### Increment Stock - Invalid
PUT http://localhost:9000/product-service/products/increment
Content-Type: application/json

{
  "productId": 100099,
  "quantity": 122
}

### Increment Stock - InValid
PUT http://localhost:9000/product-service/products/increment
Content-Type: application/json

{
  "productId": 100001,
  "quantity": -3
}


### Increment Stock - Valid
PUT http://localhost:9000/product-service/products/increment
Content-Type: application/json

{
  "productId": 100001,
  "quantity": 12
}

### Decrement stock - Very high value
PUT http://localhost:9000/product-service/products/decrement
Content-Type: application/json

{
  "productId": 100001,
  "quantity": 2000
}

### Decrement stock
PUT http://localhost:9000/product-service/products/decrement
Content-Type: application/json

{
  "productId": 100001,
  "quantity": 12
}


### Fetch All categories

GET http://localhost:9200/categories

### Create Category - Invalid data
POST http://localhost:9200/categories
Content-Type: application/json

{
  "categoryDescription": "This is a dummy category description",
  "categoryImageUrl": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}

### Create category - Valid Data
POST http://localhost:9200/categories
Content-Type: application/json

{
  "categoryName": "",
  "categoryDescription": "This is a dummy category description",
  "categoryImageUrl": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}


### Create category - Valid Data
POST http://localhost:9200/categories
Content-Type: application/json

{
  "categoryName": "Dummy Category",
  "categoryDescription": "This is a dummy category description",
  "categoryImageUrl": "https://image.shutterstock.com/image-photo/colorful-tshirts-on-hang-sale-260nw-1041488371.jpg"
}
